# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c36a4096d1947dd02e0a6ef65349481c370bffac723d6ed204cbeaccf29642f99bf304509d885ef20ad64ff5bb759c88d6d608f164e5d60813005ff5e573946

test:
  secret_key_base: 9fd5992d13ddd387c5d844cc073ae7d05c7de17713fecaf1d024d453ac4f77c5096b58b79ba6187b97ce0b97cf6d7d7f260e00a28657adc129f0479ecbfc2402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
